### ISSUE TITLE
显示启动成功,但实际未正常运作

### ISSUE THREAD

**Issue by cxh6qnbb** [luolongfei/netflix#5]
您好,使用一台刚安装好centos系统的VPS
依照文章内部署运行后
有显示
Creating network "netflix_netflix-network" with driver "bridge"
Creating redis_for_netflix ... done
Creating netflix           ... done
但功能实际未正常运作
logs目录下的日志文件也完全空白
透过输出程序日志指令则显示
<details><summary>输出程序日志</summary>
<p>

> [root@dqnyrd3s netflix]# docker-compose logs
Attaching to netflix, redis_for_netflix
netflix    | wait-for-it.sh: waiting 24 seconds for redis_for_netflix:6379
netflix    | wait-for-it.sh: redis_for_netflix:6379 is available after 0 seconds
netflix    | Traceback (most recent call last):
netflix    |   File "/app/netflix.py", line 1555, in <module>
netflix    |     Netflix = Netflix()
netflix    |   File "/app/netflix.py", line 146, in __init__
netflix    |     self.driver = webdriver.Chrome(executable_path=os.getenv('DRIVER_EXECUTABLE_FILE'), options=self.options)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
netflix    |     RemoteWebDriver.__init__(
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
netflix    |     self.start_session(capabilities, browser_profile)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
netflix    |     response = self.execute(Command.NEW_SESSION, parameters)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
netflix    |     response = self.command_executor.execute(driver_command, params)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
netflix    |     return self._request(command_info[0], url, body=data)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
netflix    |     resp = self._conn.request(method, url, body=body, headers=headers)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 118, in request
netflix    |     return self.request_encode_body(
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 217, in request_encode_body
netflix    |     return self.urlopen(method, url, **extra_kw)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 432, in urlopen
netflix    |     conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
netflix    |     return self.connection_from_context(request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 328, in connection_from_context
netflix    |     return self.connection_from_pool_key(pool_key, request_context=request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 351, in connection_from_pool_key
netflix    |     pool = self._new_pool(scheme, host, port, request_context=request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 265, in _new_pool
netflix    |     return pool_cls(host, port, **request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 196, in __init__
netflix    |     timeout = Timeout.from_float(timeout)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 190, in from_float
netflix    |     return Timeout(read=timeout, connect=timeout)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 119, in __init__
netflix    |     self._connect = self._validate_timeout(connect, "connect")
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 156, in _validate_timeout
netflix    |     raise ValueError(
netflix    | ValueError: Timeout value connect was <object object at 0x7f454189eae0>, but it must be an int, float or None.
netflix    | wait-for-it.sh: waiting 24 seconds for redis_for_netflix:6379
netflix    | wait-for-it.sh: redis_for_netflix:6379 is available after 0 seconds
netflix    | Traceback (most recent call last):
netflix    |   File "/app/netflix.py", line 1555, in <module>
netflix    |     Netflix = Netflix()
netflix    |   File "/app/netflix.py", line 146, in __init__
netflix    |     self.driver = webdriver.Chrome(executable_path=os.getenv('DRIVER_EXECUTABLE_FILE'), options=self.options)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
netflix    |     RemoteWebDriver.__init__(
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
netflix    |     self.start_session(capabilities, browser_profile)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
netflix    |     response = self.execute(Command.NEW_SESSION, parameters)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
netflix    |     response = self.command_executor.execute(driver_command, params)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
netflix    |     return self._request(command_info[0], url, body=data)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
netflix    |     resp = self._conn.request(method, url, body=body, headers=headers)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 118, in request
netflix    |     return self.request_encode_body(
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 217, in request_encode_body
netflix    |     return self.urlopen(method, url, **extra_kw)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 432, in urlopen
netflix    |     conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
netflix    |     return self.connection_from_context(request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 328, in connection_from_context
netflix    |     return self.connection_from_pool_key(pool_key, request_context=request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 351, in connection_from_pool_key
netflix    |     pool = self._new_pool(scheme, host, port, request_context=request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 265, in _new_pool
netflix    |     return pool_cls(host, port, **request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 196, in __init__
netflix    |     timeout = Timeout.from_float(timeout)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 190, in from_float
netflix    |     return Timeout(read=timeout, connect=timeout)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 119, in __init__
netflix    |     self._connect = self._validate_timeout(connect, "connect")
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 156, in _validate_timeout
netflix    |     raise ValueError(
netflix    | ValueError: Timeout value connect was <object object at 0x7f42981f48a0>, but it must be an int, float or None.
netflix    | wait-for-it.sh: waiting 24 seconds for redis_for_netflix:6379
netflix    | wait-for-it.sh: redis_for_netflix:6379 is available after 0 seconds
netflix    | Traceback (most recent call last):
netflix    |   File "/app/netflix.py", line 1555, in <module>
redis_for_netflix | 1:C 02 Jul 2023 00:26:10.472 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_for_netflix | 1:C 02 Jul 2023 00:26:10.473 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis_for_netflix | 1:C 02 Jul 2023 00:26:10.473 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_for_netflix | 1:M 02 Jul 2023 00:26:10.479 * monotonic clock: POSIX clock_gettime
redis_for_netflix | 1:M 02 Jul 2023 00:26:10.480 * Running mode=standalone, port=6379.
redis_for_netflix | 1:M 02 Jul 2023 00:26:10.480 # Server initialized
redis_for_netflix | 1:M 02 Jul 2023 00:26:10.480 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_for_netflix | 1:M 02 Jul 2023 00:26:10.480 * Loading RDB produced by version 6.2.6
redis_for_netflix | 1:M 02 Jul 2023 00:26:10.480 * RDB age 44 seconds
redis_for_netflix | 1:M 02 Jul 2023 00:26:10.480 * RDB memory usage when created 0.77 Mb
redis_for_netflix | 1:M 02 Jul 2023 00:26:10.480 # Done loading RDB, keys loaded: 0, keys expired: 0.
redis_for_netflix | 1:M 02 Jul 2023 00:26:10.480 * DB loaded from disk: 0.000 seconds
redis_for_netflix | 1:M 02 Jul 2023 00:26:10.480 * Ready to accept connections
netflix    |     Netflix = Netflix()
netflix    |   File "/app/netflix.py", line 146, in __init__
netflix    |     self.driver = webdriver.Chrome(executable_path=os.getenv('DRIVER_EXECUTABLE_FILE'), options=self.options)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
netflix    |     RemoteWebDriver.__init__(
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
netflix    |     self.start_session(capabilities, browser_profile)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
netflix    |     response = self.execute(Command.NEW_SESSION, parameters)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
netflix    |     response = self.command_executor.execute(driver_command, params)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
netflix    |     return self._request(command_info[0], url, body=data)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
netflix    |     resp = self._conn.request(method, url, body=body, headers=headers)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 118, in request
netflix    |     return self.request_encode_body(
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 217, in request_encode_body
netflix    |     return self.urlopen(method, url, **extra_kw)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 432, in urlopen
netflix    |     conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
netflix    |     return self.connection_from_context(request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 328, in connection_from_context
netflix    |     return self.connection_from_pool_key(pool_key, request_context=request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 351, in connection_from_pool_key
netflix    |     pool = self._new_pool(scheme, host, port, request_context=request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 265, in _new_pool
netflix    |     return pool_cls(host, port, **request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 196, in __init__
netflix    |     timeout = Timeout.from_float(timeout)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 190, in from_float
netflix    |     return Timeout(read=timeout, connect=timeout)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 119, in __init__
netflix    |     self._connect = self._validate_timeout(connect, "connect")
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 156, in _validate_timeout
netflix    |     raise ValueError(
netflix    | ValueError: Timeout value connect was <object object at 0x7f6c1b6558a0>, but it must be an int, float or None.
netflix    | wait-for-it.sh: waiting 24 seconds for redis_for_netflix:6379
netflix    | wait-for-it.sh: redis_for_netflix:6379 is available after 0 seconds
netflix    | Traceback (most recent call last):
netflix    |   File "/app/netflix.py", line 1555, in <module>
netflix    |     Netflix = Netflix()
netflix    |   File "/app/netflix.py", line 146, in __init__
netflix    |     self.driver = webdriver.Chrome(executable_path=os.getenv('DRIVER_EXECUTABLE_FILE'), options=self.options)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
netflix    |     RemoteWebDriver.__init__(
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
netflix    |     self.start_session(capabilities, browser_profile)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
netflix    |     response = self.execute(Command.NEW_SESSION, parameters)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
netflix    |     response = self.command_executor.execute(driver_command, params)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
netflix    |     return self._request(command_info[0], url, body=data)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
netflix    |     resp = self._conn.request(method, url, body=body, headers=headers)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 118, in request
netflix    |     return self.request_encode_body(
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 217, in request_encode_body
netflix    |     return self.urlopen(method, url, **extra_kw)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 432, in urlopen
netflix    |     conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
netflix    |     return self.connection_from_context(request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 328, in connection_from_context
netflix    |     return self.connection_from_pool_key(pool_key, request_context=request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 351, in connection_from_pool_key
netflix    |     pool = self._new_pool(scheme, host, port, request_context=request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 265, in _new_pool
netflix    |     return pool_cls(host, port, **request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 196, in __init__
netflix    |     timeout = Timeout.from_float(timeout)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 190, in from_float
netflix    |     return Timeout(read=timeout, connect=timeout)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 119, in __init__
netflix    |     self._connect = self._validate_timeout(connect, "connect")
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 156, in _validate_timeout
netflix    |     raise ValueError(
netflix    | ValueError: Timeout value connect was <object object at 0x7f5ef7d148a0>, but it must be an int, float or None.
netflix    | wait-for-it.sh: waiting 24 seconds for redis_for_netflix:6379
netflix    | wait-for-it.sh: redis_for_netflix:6379 is available after 0 seconds
netflix    | Traceback (most recent call last):
netflix    |   File "/app/netflix.py", line 1555, in <module>
netflix    |     Netflix = Netflix()
netflix    |   File "/app/netflix.py", line 146, in __init__
netflix    |     self.driver = webdriver.Chrome(executable_path=os.getenv('DRIVER_EXECUTABLE_FILE'), options=self.options)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
netflix    |     RemoteWebDriver.__init__(
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
netflix    |     self.start_session(capabilities, browser_profile)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
netflix    |     response = self.execute(Command.NEW_SESSION, parameters)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
netflix    |     response = self.command_executor.execute(driver_command, params)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
netflix    |     return self._request(command_info[0], url, body=data)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
netflix    |     resp = self._conn.request(method, url, body=body, headers=headers)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 118, in request
netflix    |     return self.request_encode_body(
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 217, in request_encode_body
netflix    |     return self.urlopen(method, url, **extra_kw)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 432, in urlopen
netflix    |     conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
netflix    |     return self.connection_from_context(request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 328, in connection_from_context
netflix    |     return self.connection_from_pool_key(pool_key, request_context=request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 351, in connection_from_pool_key
netflix    |     pool = self._new_pool(scheme, host, port, request_context=request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 265, in _new_pool
netflix    |     return pool_cls(host, port, **request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 196, in __init__
netflix    |     timeout = Timeout.from_float(timeout)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 190, in from_float
netflix    |     return Timeout(read=timeout, connect=timeout)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 119, in __init__
netflix    |     self._connect = self._validate_timeout(connect, "connect")
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 156, in _validate_timeout
netflix    |     raise ValueError(
netflix    | ValueError: Timeout value connect was <object object at 0x7f4cb4fed8a0>, but it must be an int, float or None.
netflix    | wait-for-it.sh: waiting 24 seconds for redis_for_netflix:6379
netflix    | wait-for-it.sh: redis_for_netflix:6379 is available after 0 seconds
netflix    | Traceback (most recent call last):
netflix    |   File "/app/netflix.py", line 1555, in <module>
netflix    |     Netflix = Netflix()
netflix    |   File "/app/netflix.py", line 146, in __init__
netflix    |     self.driver = webdriver.Chrome(executable_path=os.getenv('DRIVER_EXECUTABLE_FILE'), options=self.options)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
netflix    |     RemoteWebDriver.__init__(
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
netflix    |     self.start_session(capabilities, browser_profile)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
netflix    |     response = self.execute(Command.NEW_SESSION, parameters)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
netflix    |     response = self.command_executor.execute(driver_command, params)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
netflix    |     return self._request(command_info[0], url, body=data)
netflix    |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
netflix    |     resp = self._conn.request(method, url, body=body, headers=headers)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 118, in request
netflix    |     return self.request_encode_body(
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 217, in request_encode_body
netflix    |     return self.urlopen(method, url, **extra_kw)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 432, in urlopen
netflix    |     conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
netflix    |     return self.connection_from_context(request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 328, in connection_from_context
netflix    |     return self.connection_from_pool_key(pool_key, request_context=request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 351, in connection_from_pool_key
netflix    |     pool = self._new_pool(scheme, host, port, request_context=request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 265, in _new_pool
netflix    |     return pool_cls(host, port, **request_context)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 196, in __init__
netflix    |     timeout = Timeout.from_float(timeout)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 190, in from_float
netflix    |     return Timeout(read=timeout, connect=timeout)
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 119, in __init__
netflix    |     self._connect = self._validate_timeout(connect, "connect")
netflix    |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 156, in _validate_timeout
netflix    |     raise ValueError(
netflix    | ValueError: Timeout value connect was <object object at 0x7fcd36e648a0>, but it must be an int, float or None.

</p>
</details> 

方便询问一下是哪一步操作错误吗

**Comment by luolongfei** [comment]
把错误消息贴出来

**Comment by cxh6qnbb** [comment]
除了手动输入docker-compose logs所显示的内容外
没有提示其他消息了

**Comment by luolongfei** [comment]
docker compose ps

**Comment by cxh6qnbb** [comment]
> [root@instance-20210410-1116 netflix]# docker compose ps
NAME                IMAGE                  COMMAND                  SERVICE             CREATED             STATUS              PORTS
netflix             netflix_netflix        "sh -c docker-entryp…"   netflix             35 seconds ago      Up 1 second         
redis_for_netflix   redis:6.2.6-bullseye   "docker-entrypoint.s…"   redis               39 seconds ago      Up 35 seconds       6379/tcp
[root@instance-20210410-1116 netflix]# docker compose ps
NAME                IMAGE                  COMMAND                  SERVICE             CREATED             STATUS                         PORTS
netflix             netflix_netflix        "sh -c docker-entryp…"   netflix             3 minutes ago       Restarting (1) 3 seconds ago   
redis_for_netflix   redis:6.2.6-bullseye   "docker-entrypoint.s…"   redis               3 minutes ago       Up 3 minutes                   6379/tcp

**Comment by luolongfei** [comment]
docker-compose logs 里有没有看到错误信息
