### ISSUE TITLE
根据教程启动docker时报错，以下是错误信息

### ISSUE THREAD

**Issue by neeko8** [luolongfei/netflix#7]
wait-for-it.sh: waiting 24 seconds for redis_for_netflix:6379
wait-for-it.sh: redis_for_netflix:6379 is available after 0 seconds
Traceback (most recent call last):
  File "/app/netflix.py", line 1555, in <module>
    Netflix = Netflix()
  File "/app/netflix.py", line 146, in __init__
    self.driver = webdriver.Chrome(executable_path=os.getenv('DRIVER_EXECUTABLE_FILE'), options=self.options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 144, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 432, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 328, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 351, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 265, in _new_pool
    return pool_cls(host, port, **request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 195, in __init__
    timeout = Timeout.from_float(timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 186, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 115, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 152, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x7f7857a6bae0>, but it must be an int, float or None.
wait-for-it.sh: waiting 24 seconds for redis_for_netflix:6379
wait-for-it.sh: redis_for_netflix:6379 is available after 0 seconds
Traceback (most recent call last):
  File "/app/netflix.py", line 1555, in <module>
    Netflix = Netflix()
  File "/app/netflix.py", line 146, in __init__
    self.driver = webdriver.Chrome(executable_path=os.getenv('DRIVER_EXECUTABLE_FILE'), options=self.options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 144, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 432, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 328, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 351, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 265, in _new_pool
    return pool_cls(host, port, **request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 195, in __init__
    timeout = Timeout.from_float(timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 186, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 115, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 152, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x7fbdb14698a0>, but it must be an int, float or None.
wait-for-it.sh: waiting 24 seconds for redis_for_netflix:6379
wait-for-it.sh: redis_for_netflix:6379 is available after 0 seconds
Traceback (most recent call last):
  File "/app/netflix.py", line 1555, in <module>
    Netflix = Netflix()
  File "/app/netflix.py", line 146, in __init__
    self.driver = webdriver.Chrome(executable_path=os.getenv('DRIVER_EXECUTABLE_FILE'), options=self.options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 144, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 432, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 328, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 351, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 265, in _new_pool
    return pool_cls(host, port, **request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 195, in __init__
    timeout = Timeout.from_float(timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 186, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 115, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 152, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x7fe747b848a0>, but it must be an int, float or None.
wait-for-it.sh: waiting 24 seconds for redis_for_netflix:6379
wait-for-it.sh: redis_for_netflix:6379 is available after 0 seconds
Traceback (most recent call last):
  File "/app/netflix.py", line 1555, in <module>
    Netflix = Netflix()
  File "/app/netflix.py", line 146, in __init__
    self.driver = webdriver.Chrome(executable_path=os.getenv('DRIVER_EXECUTABLE_FILE'), options=self.options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 144, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 432, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 328, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 351, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 265, in _new_pool
    return pool_cls(host, port, **request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 195, in __init__
    timeout = Timeout.from_float(timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 186, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 115, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 152, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x7f2152bb38a0>, but it must be an int, float or None.
wait-for-it.sh: waiting 24 seconds for redis_for_netflix:6379
wait-for-it.sh: redis_for_netflix:6379 is available after 0 seconds
Traceback (most recent call last):
  File "/app/netflix.py", line 1555, in <module>
    Netflix = Netflix()
  File "/app/netflix.py", line 146, in __init__
    self.driver = webdriver.Chrome(executable_path=os.getenv('DRIVER_EXECUTABLE_FILE'), options=self.options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 144, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 432, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 328, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 351, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 265, in _new_pool
    return pool_cls(host, port, **request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 195, in __init__
    timeout = Timeout.from_float(timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 186, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 115, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 152, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x7fad66ae58a0>, but it must be an int, float or None.
wait-for-it.sh: waiting 24 seconds for redis_for_netflix:6379
wait-for-it.sh: redis_for_netflix:6379 is available after 0 seconds
Traceback (most recent call last):
  File "/app/netflix.py", line 1555, in <module>
    Netflix = Netflix()
  File "/app/netflix.py", line 146, in __init__
    self.driver = webdriver.Chrome(executable_path=os.getenv('DRIVER_EXECUTABLE_FILE'), options=self.options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 144, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 432, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 328, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 351, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 265, in _new_pool
    return pool_cls(host, port, **request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 195, in __init__
    timeout = Timeout.from_float(timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 186, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 115, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 152, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x7fc67608f8a0>, but it must be an int, float or None.
wait-for-it.sh: waiting 24 seconds for redis_for_netflix:6379
wait-for-it.sh: redis_for_netflix:6379 is available after 0 seconds
Traceback (most recent call last):
  File "/app/netflix.py", line 1555, in <module>
    Netflix = Netflix()
  File "/app/netflix.py", line 146, in __init__
    self.driver = webdriver.Chrome(executable_path=os.getenv('DRIVER_EXECUTABLE_FILE'), options=self.options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 144, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 432, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 328, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 351, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 265, in _new_pool
    return pool_cls(host, port, **request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 195, in __init__
    timeout = Timeout.from_float(timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 186, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 115, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 152, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x7f029c32f8a0>, but it must be an int, float or None.
wait-for-it.sh: waiting 24 seconds for redis_for_netflix:6379
wait-for-it.sh: redis_for_netflix:6379 is available after 0 seconds
Traceback (most recent call last):
  File "/app/netflix.py", line 1555, in <module>
    Netflix = Netflix()
  File "/app/netflix.py", line 146, in __init__
    self.driver = webdriver.Chrome(executable_path=os.getenv('DRIVER_EXECUTABLE_FILE'), options=self.options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 144, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.9/site-packages/urllib3/_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 432, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 328, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 351, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 265, in _new_pool
    return pool_cls(host, port, **request_context)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 195, in __init__
    timeout = Timeout.from_float(timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 186, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 115, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 152, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x7f271a9718a0>, but it must be an int, float or None.
看了半天不知道如何解决

**Comment by XRFate** [comment]
这个为什么关闭了，我也遇到一样的问题了

**Comment by XRFate** [comment]
排查了一下是 chrome 没安装成功 `ARG CHROME_DOWNLOAD_URL=http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb` 这个链接404了，然后docker compose run 里面` rm -f /tmp/chrome.deb `是最后一句
所以没抛异常，还在看咋解决

**Comment by luolongfei** [comment]
那个版本的浏览器，谷歌官方不再提供了

**Comment by XRFate** [comment]
这个报错也找到了 requirement.txt 加上 `urllib3>=1.26.15,<2`
